version: '3.1'
services:

  config:
    image: configjava
    restart: always
    ports:
      - 8888:8888
    networks:
      - mi_red

  eureka:
    image: eurekajava
    restart: always
    ports:
      - 8761:8761
    depends_on:
      - config
    networks:
      - mi_red

  #estudiante:
    #image: estudiantejava
    #restart: always
    #ports:
      #- 8090:8090
    #depends_on:
      #- eureka
      #- config
    #networks:
      #- my-network

volumes:
  myvolume:
networks:
  mi_red:
    driver: bridge
